import Head from "next/head";

import { PostsCarousel } from "@src/components/post/PostsCarousel";
import { Header } from "@src/components/layouts/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto min-h-screen border-slate-500 md:max-w-2xl md:border-x">
          <Header />
          <PostsCarousel />
        </div>
      </main>
    </>
  );
}
